title: <p align="center"> Akash Sharma </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/akash-sharma-814243136/">LinkedIn</a> |
  <a href="https://github.com/akashsharma71191">GitHub</a>
  
  <br>   
  • A result oriented professional with 9 years of experience in software development using BigData, Hadoop,Apache Spark technologies
  • Experience in Analysis, Coding, Integration, and Implementation of larger-scale Business Applications.
  <br>
  </p>



theme: jekyll-theme-minimal
